### ISSUE TITLE
Portrait / upright videos

### ISSUE THREAD

**Issue by bdoubleu86** [justsoft/video_thumbnail#11]
I am not getting correct thumbnails from portrait videos.
For this issue I did not find a solution with your plugin.
Is this issue know? Do you know a solution?

**Comment by justsoft** [comment]
Could you please provide a video URL I can try?

**Comment by bdoubleu86** [comment]
You can try: http://files.danceapp.de/IMG_6078.MOV

It is a very short video tho.

**Comment by justsoft** [comment]
I changed the MaxHeightOrWidth to MaxHeight and MaxWidth, will submit tomorrow.

**Comment by justsoft** [comment]
Please check the newly updated 0.2.0, let me know the issue has been fixed.

**Comment by bdoubleu86** [comment]
I am still having this issue with the distorted thumbnail with this:
```
    final String thumbnail = await VideoThumbnail.thumbnailFile(
        video: filePath,
        thumbnailPath: target,
        imageFormat: ImageFormat.PNG,
        maxHeight: 0,
        maxWidth: 0,
        quality: 80,
        timeMs: 500);
```

**Comment by justsoft** [comment]
For this parameters you should get the original dimensions of the video.
Please double check your video, also try another video.

**Comment by bdoubleu86** [comment]
It is not working with the video mentioned above. Does it work for you with this video? Appreciate your help!

**Comment by justsoft** [comment]
Please try your video URL by the example: https://github.com/justsoft/video_thumbnail/tree/master/example

**Comment by bdoubleu86** [comment]
You are right, my video works with your example!
Somehow now I get an error with invoke method. I think your code is fine. However, do you know how to solve it? I tried already `flutter clean`, but still getting this:
```
E/flutter (11932): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail)
E/flutter (11932): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (11932): <asynchronous suspension>
E/flutter (11932): #1      VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:27)
```

Appreciate any help!

**Comment by justsoft** [comment]
Try to install MX player or any media player which comes with video codecs, and try again.
